config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"

  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  scope module: :public do
    resources :cart_items, only:[:index, :create, :update, :destroy]
    resources :books, only:[:index, :show] do
      resources :book_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :orders, only:[:index,:new,:show,:create]
    resources :addresses, only:[:index,:edit,:update,:destroy,:create]
    resources :customers, only:[:show,:edit,:update]
  end

  delete '/cart_items', to: 'public/cart_items#destroy_all',as: 'all_destroy'
  post '/confirm', to: 'public/orders#confirm',as: 'confirm'
  get '/thanks', to: 'public/orders#thanks',as: 'thanks'
  patch '/out', to: 'public/customers#out'
  get '/quit', to: 'public/customers#quit', as: 'quit'
  get '/rank', to: 'public/books#rank', as: 'rank'
  get '/populer', to: 'public/books#populer', as: 'populer'

# 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admins do
    resources :books, only:[:index,:show,:edit,:new,:update,:create]
    resources :genres, only:[:index,:edit,:update,:create]
    resources :customers, only:[:index, :update]
  end

  get '/search', to: 'searches#search'
  get '/genresearch', to: 'searches#genresearch'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image_id

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def get_image
    unless image_id.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image_id.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image_id
  end

  # いいね機能
  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end
  #検索機能
  def self.search_for(content)
    Book.where('name LIKE ?', '%' + content + '%')
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :customer
  belongs_to :book
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :book

  # 小計
  def subtotal
    book.price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # 退会ユーザーはログインできなくする
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/data_page.rb
class DataPage < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :book
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many:book,dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :ordered_items,dependent: :destroy
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order
  belongs_to :book
end

app/controllers/addresses_controller.rb
class Public::AddressesController < ApplicationController
  def new
    @address = Address.new
  end

  def create
    @address = Address.new(address_params)
    @address.customer_id = current_customer.id
    @addresses = current_customer.addresses
    if @address.save
      redirect_to addresses_path
    else
      render :index
    end
  end

  def index
    @address = Address.new
    @address.customer_id = current_customer.id
    @addresses = current_customer.addresses
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    @address.update(address_params)
    redirect_to addresses_path
  end

  def destroy
    address = Address.find(params[:id])
    address.destroy
    redirect_to addresses_path
  end

  private

  def address_params
    params.require(:address).permit(:postal_code, :address, :name)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
   @book = Book.where(is_active: true).order(created_at: :desc).limit(4)
   @all_ranks = Book.find(Favorite.group(:book_id).order('count(book_id) desc').limit(4).pluck(:book_id))
   @genres = Genre.all
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
		@content = params[:content]
		@book = Book.where(is_active: true).search_for(@content)
	end

	def genresearch
		@content = params[:content]
		@genre = Genre.find_by(name: @content)
		@books = Book.where(is_active: true, genre_id: @genre.id)
	end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/data_pages_helper.rb
module DataPagesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/homes/top.html.erb
<div class="row mt-5">
  <div class="col-1">
  </div>
  <div class="col-xl-2">
    <ul class="list-group">
      <li class="list-group-item disabled" aria-disabled="true">ジャンル検索</li>
    <% @genres.each do |genre| %>
      <li class="list-group-item"><%= link_to genre.name, genresearch_path(content: genre.name) %></li>
    <% end %>
  </div>
  <div>
    <h1>新着</h1>
    <div class="row">
      <% @book.each do |book| %>
        <div class="col-xl-3 col-md-6">
          <% if book.image_id.attached? %>
            <%= image_tag book.image_id, size: "180x180" %>
          <% else %>
            <%= image_tag 'no_image.jpg', size: "180x180" %>
          <% end %>
          <p><%= link_to book.name, book_path(book.id) %></p>
          <p>¥<%= book.price.to_s(:delimited) %></p>
        </div>
      <% end %>
      <div class="col-xl-3 col-md-6">
        <%= link_to "一覧を見る", populer_path %>
      </div>
    </div>
    <div class="row mt-5 ">
      <h1>人気ランキング</h1>
    </div>
    <div class="row">
      <% count = 1 %>
      <% @all_ranks.each.with_index(1) do |rank, i| %>
        <div class="col-xl-3 col-md-6">
          <h4><%= count %>位</h4>
          <% if rank.image_id.attached? %>
            <%= image_tag rank.image_id, size: "180x180" %>
          <% else %>
            <%= image_tag 'no_image.jpg', size: "180x180" %>
          <% end %>
          <p><%= link_to rank.name, book_path(rank.id) %></p>
          <p>¥<%= rank.price.to_s(:delimited) %></p>
          <% count += 1 %>
        </div>
      <% end %>
      <div class="col-xl-3 col-md-6">
        <%= link_to "一覧を見る", rank_path %>
      </div>
    </div>
  </div>

app/views/searches/_form.html.erb
<%= form_with url: search_path, method: :get, local: true do |f| %>
    <%= f.text_field :content %>
    <%= f.submit "検索" %>
  <% end %>

app/views/searches/genresearch.html.erb
<div class="container mt-3 mx-auto">
  <div class="row">
    <h1>商品一覧</h1>
  </div>
<div class="row justify-content-center">
    <div class="col-xl-3 col-md-3">
      <% @books.each do |book| %>
        <% if book.image_id.attached? %>
          <%= image_tag book.image_id, size: "200x200" %>
        <% else %>
          <%= image_tag 'no_image.jpg', size: "200x200" %>
        <% end %>
        <p><%= link_to book.name, book_path(book.id) %></p>
        <p>¥<%= book.price.to_s(:delimited) %></p>
      <% end %>
    </div>
</div>

app/views/searches/search.html.erb
<% if customer_signed_in? %>
 <div class="container mt-3 mx-auto">
    <div class="row">
      <h3>検索結果"<%= @content %>"</h3>
    </div>
    <div class="row justify-content-center">
      <% @book.each do |book| %>
      <div class="col-xl-3 col-md-3">
        <% if book.image_id.attached? %>
          <%= image_tag book.image_id, size: "200x200" %>
        <% else %>
          <%= image_tag 'no_image.jpg', size: "200x200" %>
        <% end %>
        <p><%= link_to book.name, book_path(book.id) %></p>
        <p>¥<%= book.price.to_s(:delimited) %></p>
      </div>
      <% end %>
    </div>
  </div>
<% elsif admin_signed_in? %>
  <div class="container mt-3 mx-auto">
    <div class="row">
      <h3>検索結果 "<%= @content %>"</h3>
    </div>
    <div class="row justify-content-center">
      <% @book.each do |book| %>
      <div class="col-xl-3 col-md-3">
        <% if book.image_id.attached? %>
          <%= image_tag book.image_id, size: "200x200" %>
        <% else %>
          <%= image_tag 'no_image.jpg', size: "200x200" %>
        <% end %>
        <p><%= link_to book.name, admin_item_path(book.id) %></p>
        <p>¥<%= book.price.to_s(:delimited) %></p>
      </div>
      <% end %>
    </div>
　</div>
<% end %>