config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"

  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  scope module: :public do
    resources :cart_items, only:[:index, :create, :update, :destroy]
    resources :books, only:[:index, :show] do
      resources :book_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :orders, only:[:index,:new,:show,:create]
    resources :addresses, only:[:index,:edit,:update,:destroy,:create]
    resources :customers, only:[:show,:edit,:update]
  end

  delete '/cart_items', to: 'public/cart_items#destroy_all',as: 'all_destroy'
  post '/confirm', to: 'public/orders#confirm',as: 'confirm'
  get '/thanks', to: 'public/orders#thanks',as: 'thanks'
  patch '/out', to: 'public/customers#out'
  get '/quit', to: 'public/customers#quit', as: 'quit'
  get '/rank', to: 'public/books#rank', as: 'rank'
  get '/populer', to: 'public/books#populer', as: 'populer'

# 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admins do
    resources :books, only:[:index,:show,:edit,:new,:update,:create]
    resources :genres, only:[:index,:edit,:update,:create]
    resources :customers, only:[:index, :update]
  end

  get '/search', to: 'searches#search'
  get '/genresearch', to: 'searches#genresearch'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image_id

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def get_image
    unless image_id.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image_id.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image_id
  end

  # いいね機能
  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end
  #検索機能
  def self.search_for(content)
    Book.where('name LIKE ?', '%' + content + '%')
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :customer
  belongs_to :book
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :book

  # 小計
  def subtotal
    book.price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # 退会ユーザーはログインできなくする
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/data_page.rb
class DataPage < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :book
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many:book,dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :ordered_items,dependent: :destroy
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order
  belongs_to :book
end

app/controllers/admins/books_controller.rb
class Admins::BooksController < ApplicationController
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.genre_id = params[:book][:genre_id]
      if @book.save
        redirect_to admins_book_path(@book.id)
      else
        render :new
      end
  end

  def index
    @books = Book.all
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book=Book.find(params[:id])
      if @book.update(book_params)
        redirect_to admins_book_path
      else
        render :new
      end
  end

  def show
    @book = Book.find(params[:id])
  end

  def destroy
  end

  private

  def  book_params
    params.require(:book).permit(:image_id, :name, :price, :is_active, :synopsis, :genre_id, :author)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
   @book = Book.where(is_active: true).order(created_at: :desc).limit(4)
   @all_ranks = Book.find(Favorite.group(:book_id).order('count(book_id) desc').limit(4).pluck(:book_id))
   @genres = Genre.all
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
		@content = params[:content]
		@book = Book.where(is_active: true).search_for(@content)
	end

	def genresearch
		@content = params[:content]
		@genre = Genre.find_by(name: @content)
		@books = Book.where(is_active: true, genre_id: @genre.id)
	end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admins/books_helper.rb
module Admins::BooksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/data_pages_helper.rb
module DataPagesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admins/books/edit.html.erb
<div class="container">
  <h1>編集</h1>
  <%= form_with model: @book, url: admins_book_path, method: :patch, local: true do |f| %>
    イメージ画像
    <p><%= f.file_field :image_id, accept: "image/*" %></p>
    <div class="form-group">
      <lavel>本のタイトル</lavel>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <lavel>作者</lavel>
      <%= f.text_field :author, class: "form-control" %>
    </div>
    <div class="form-group">
      <lavel>本のあらすじ</lavel>
      <%= f.text_area :synopsis, class: "form-control" %>
    </div>
    <div class="form-group">
      <lavel>値段</lavel>
      <%= f.number_field :price, class: "form-control" %>
    </div>
    <div class="form-group">
      <lavel>ジャンル</lavel>
      <%= f.collection_select :genre_id, Genre.all, :id, :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <p>販売ステータス</p>
      <%= f.radio_button:is_active,true %>
      <%= f.label:"販売中" %>
      <%= f.radio_button:is_active,false %>
      <%= f.label:"販売停止" %>
    </div>
    <div>
      <%= f.submit"保存", class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/admins/books/index.html.erb
<div class="container">
  <div class="row">
    <% @books.each do |book| %>
      <div class="col-xl-3 col-md-6">
        <% if book.image_id.attached? %>
          <%= image_tag book.image_id, size: "180x180" %>
        <% else %>
          <%= image_tag 'no_image.jpg', size: "180x180" %>
        <% end %>
        <p><%= link_to book.name, admins_book_path(book.id) %></p>
        <p>¥<%= book.price.to_s(:delimited) %></p>
        <p><%= book.genre.name %></p>
        <% if book.is_active == true %>
          販売中
        <% else %>
          販売停止中
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/admins/books/new.html.erb
<div class="container mt-3">
  <h1>本の新規登録</h1>
  <%= form_with model: @book, url: admins_books_path, method: :post, local: true do |f| %>
    <p>イメージ画像</p>
    <%= f.file_field :image_id, accept: "image/*" %>
    <p>本のタイトル</p>
    <%= f.text_field :name %>
    <p>作者</p>
    <%= f.text_field :author %>
    <p>本のあらすじ</p>
    <%= f.text_area :synopsis %>
    <p>値段</p>
    <%= f.number_field :price %>
    <p>ジャンル</p>
    <%= f.collection_select :genre_id, Genre.all, :id, :name %>
    <p>販売ステータス</p>
    <%= f.radio_button:is_active, true %>
    <%= f.label:"販売中" %>
    <%= f.radio_button:is_active, false %>
    <%= f.label:"販売停止" %>
    <%= f.submit"投稿" %>
  <% end %>
</div>

app/views/admins/books/show.html.erb
<div class="container">
  <% if @book.image_id.attached? %>
    <%= image_tag @book.image_id, size: "200x200" %>
  <% else %>
    <%= image_tag 'no_image.jpg', size: "200x200" %>
  <% end %>
  <p>タイトル</p>
  <%= @book.name %>
  <p>作者</p>
  <%= @book.author %>
  <p>あらすじ</p>
  <%= @book.synopsis %>
  <p>ジャンル</p>
  <%= @book.genre.name %>
  <p>値段</p>
  <%= @book.price.to_s(:delimited) %>
  <p>販売ステータス</p>
  <% if @book.is_active == true %>
    販売中</br>
  <% else %>
    販売停止中
  <% end %></br>
  <%= link_to "編集", edit_admins_book_path(@book.id), class: "btn btn-primary" %>
</div>