config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"

  # 顧客用
  devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  scope module: :public do
    resources :cart_items, only:[:index, :create, :update, :destroy]
    resources :books, only:[:index, :show] do
      resources :book_comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
    resources :orders, only:[:index,:new,:show,:create]
    resources :addresses, only:[:index,:edit,:update,:destroy,:create]
    resources :customers, only:[:show,:edit,:update]
  end

  delete '/cart_items', to: 'public/cart_items#destroy_all',as: 'all_destroy'
  post '/confirm', to: 'public/orders#confirm',as: 'confirm'
  get '/thanks', to: 'public/orders#thanks',as: 'thanks'
  patch '/out', to: 'public/customers#out'
  get '/quit', to: 'public/customers#quit', as: 'quit'
  get '/rank', to: 'public/books#rank', as: 'rank'
  get '/populer', to: 'public/books#populer', as: 'populer'

# 管理者用
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admins do
    resources :books, only:[:index,:show,:edit,:new,:update,:create]
    resources :genres, only:[:index,:edit,:update,:create]
    resources :customers, only:[:index, :update]
  end

  get '/search', to: 'searches#search'
  get '/genresearch', to: 'searches#genresearch'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image_id

  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  def get_image
    unless image_id.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image_id.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image_id
  end

  # いいね機能
  def favorited_by?(customer)
    favorites.exists?(customer_id: customer.id)
  end
  #検索機能
  def self.search_for(content)
    Book.where('name LIKE ?', '%' + content + '%')
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :customer
  belongs_to :book
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :book

  # 小計
  def subtotal
    book.price * amount
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # 退会ユーザーはログインできなくする
  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/data_page.rb
class DataPage < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :customer
  belongs_to :book
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many:book,dependent: :destroy
end

app/models/order.rb
class Order < ApplicationRecord

  has_many :ordered_items,dependent: :destroy
  belongs_to :customer

  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order
  belongs_to :book
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
   @book = Book.where(is_active: true).order(created_at: :desc).limit(4)
   @all_ranks = Book.find(Favorite.group(:book_id).order('count(book_id) desc').limit(4).pluck(:book_id))
   @genres = Genre.all
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/data_pages_helper.rb
module DataPagesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark bg-gradient text-white">
   <div class="container">
    <% if admin_signed_in? %>
     <a class="navbar-brand navbar-left" href="/admins/books"><%= image_tag('bookers_shop.png') %></a>
    <% else %>
     <a class="navbar-brand navbar-left" href="/"><%= image_tag('bookers_shop.png') %></a>
    <% end %>
     <nav class="d-flex align-items-center">
       <ul class="nav navbar-nav navbar-right">
         <% if admin_signed_in? %>
         <li class="nav-item">
           <%= link_to admins_customers_path do %><span class="text-light text-white nav-link"><i class="fas fa-regular fa-user"></i>会員一覧</span><% end %>
         </li>
         <li class="nav-item">
           <%= link_to new_admins_book_path do %><span class="text-light text-white nav-link"><i class="fas fa-book"></i>商品投稿</span><% end %>
         </li>
         <li>
           <%= link_to admins_genres_path do %><span class="text-light text-white nav-link"><i class="fas fa-tree"></i>ジャンル一覧</span><% end %>
         </li>
         <li>
           <%= link_to destroy_admin_session_path, method: :delete do %><span class="text-light text-white nav-link"><i class="fas fa-sign-out-alt"></i>ログアウト</span><% end %>
         </li>
         <% elsif customer_signed_in? %>
          <li>
           <%= link_to customer_path(current_customer) do %><span class="text-light text-white nav-link"><i class="fas fa-regular fa-user"></i>マイページ</span><% end %>
         </li>
         <li>
           <%= link_to orders_path do %><span class="text-light text-white nav-link"><i class="fas fa-book"></i>本棚</span><% end %>
         </li>
         <li>
           <%= link_to cart_items_path do %><span class="text-light text-white nav-link"><i class="fas fa-shopping-cart"></i>カート</span><% end %>
         </li>
         <li>
           <%= link_to destroy_customer_session_path, method: :delete do %><span class="text-light text-white nav-link"><i class="fas fa-sign-out-alt"></i>ログアウト</span><% end %>
         </li>
         <% else %>
         <li>
           <%= link_to new_customer_registration_path do %><span class="text-light text-white nav-link"><i class="fas fa-user-plus"></i>新規登録</span><% end %>
         </li>
         <li>
           <%= link_to new_customer_session_path do %><span class="text-light text-white nav-link"><i class="fas fa-sign-in-alt"></i>ログイン</span><% end %>
         </li>
         <% end %>
      </ul>
      <% if admin_signed_in? %>
      <% else %>
       <%= render 'searches/form', book: @book %>
      <% end %>
    </nav>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <%=render 'layouts/header'%>
  </header>

  <body>
    <%= yield %>
  </body>
</html>